# Generated by Django 6.0 on 2026-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0003_alter_message_options_remove_attachment_file_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(default="New conversation", max_length=200),
        ),
    ]
